CONFIG_ZMK_SPLIT=y

# sleep 
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000
CONFIG_ZMK_IDLE_TIMEOUT=30000

# mouse
CONFIG_ZMK_MOUSE=y

# battery
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y
CONFIG_ZMK_BATTERY_REPORTING=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y

# logging
CONFIG_ZMK_LOG_LEVEL_DBG=n
CONFIG_ZMK_USB_LOGGING=n
